### ISSUE TITLE
Issue with client ID when using SPA like inertia

### ISSUE THREAD

**Issue by graphem** [ably/laravel-broadcaster#45] opened 2024-06-06 18:46 UTC
Posting something someone already posted on stackoverflow, anyone with same issue?

-------------
I'm using ably for broadcasting notifications in my admin panel, I've followed this repo https://github.com/ably/laravel-broadcaster, to setup ably/laravel-broadcaster and ably larvel echo for the client side I did ably laravel echo configuration in bootstrap.js as mentioned exactly in the repo

import Echo from '@ably/laravel-echo';
import * as Ably from 'ably';

window.Ably = Ably;
window.Echo = new Echo({
    broadcaster: 'ably',
    disconnectedRetryTimeout: 500
});
window.Echo.connector.ably.connection.on(stateChange => {
    console.log(stateChange.current);
    // if (stateChange.current === 'connected') {
    //     console.log('connected to ably server');
    // }
});
everything works fine and notification is being broadcasted and received, but after the user login in my app laravel echo connection failes cuz of a clientId mismatch

Ably: Connection state: failed; reason: [ErrorInfo2: Mismatched clientId for existing connection; statusCode=401; code=40102; see https://help.ably.io/error/40102 ]
if I refreshed the page everything works fine again, it looks like after the client login, ably isn't updating the client id

Note 1: it worth mentioning that I'm using laravel inertia with vue to build my SPA applications

can anyone help? actually I don't know where to start

-------------------

I am not sure if we can force the client_id to ably as usually the laravel broadcasting auth takes care of this

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4828) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment] 2024-06-06 19:12
Hi @graphem thanks for raising the issue! 
Seems auth is not setup properly at server side. You might like to go through this comment 
https://github.com/ably-forks/laravel-echo/issues/36#issuecomment-2119833011. Also, I would like you to check https://github.com/ably-forks/laravel-echo?tab=readme-ov-file#working-with-laravel-sanctum-support-channel-auth-using-custom-implementation.

**Comment by sacOO7** [comment] 2024-06-07 04:13
As a starter, you might like to checkout https://github.com/ably-labs/laravel-broadcast-app. You can run the app using docker.

**Comment by sacOO7** [comment] 2024-06-07 14:56
I didn't get that `clientId` gets reused when not logged in. Does this mean user has `clientId` before logging in. Even if user has one, it should get updated for the next ably connection or channel attach request ( If we are making one ) -> https://github.com/ably/laravel-broadcaster/blob/83cc6bf242f9d1533ce49dbf077820426f08b15e/src/AblyBroadcaster.php#L227. 
I would say the problem is happening because user switching is happening without explicit logout. Can you confirm that you are using guest user before explicit login? If that's the case, then there might be a case where this error can arise.
Since, connection + channel permisions are assigned to given user, it cannot be reused for other user. I would suggest that you logout guest user ( which has user id ) before logging in using another user.

**Comment by graphem** [comment] 2024-06-07 15:02
From my investigation when using Inertia as SPA, if the Echo is in the bootstrap, then a client_id = null connection is created, then after login if redirected to a page were we call join channel properties, we get the error cause it seems it tries to reuse the connection with the client_id = null but with a now token with the client_id = user_id. When in a non SPA setup this would work fine cause the bootstrap will be reloaded a new connection created.

**Comment by sacOO7** [comment] 2024-06-07 15:15
Also, We do have a working laravel broadcaster app https://github.com/ably-labs/laravel-broadcast-app/. It does seem to use SPA, can you double check

**Comment by AmirHaroun1** [comment] 2024-06-15 15:43
i'm facing this issue too, any solutions ???

**Comment by sacOO7** [comment] 2024-07-13 16:25
Link to internal discussion -> https://ably-real-time.slack.com/archives/C8SPU4589/p1720522240507579

**Closed** 2024-07-15 08:37 UTC
Labels: bug

**Comment by sacOO7** [comment] 2024-07-15 08:55
Hi @graphem @AmirHaroun1 we have merged PR for the fix. Expect release soon 👍

**Comment by sacOO7** [comment] 2024-07-15 12:17
Hi @graphem @AmirHaroun1 we have released fix in [laravel echo](https://github.com/ably-forks/laravel-echo/releases/tag/ably-echo-1.0.5). Do update the library 
```
npm install @ably/laravel-echo 1.0.5
```

**Comment by sacOO7** [comment] 2024-07-15 12:20
Also, give a read for https://github.com/ably-forks/laravel-echo#:~:text=If%20you%20are%20using%20SPA%20on%20client%20side
